install.packages("excelR")
install.packages(c("igraph", "ggdag"))
install.packages("shinythemes")
install.packages("colourpicker")
install.packages("shinydashboard")
install.packages("shinyFiles")
install.packages("fs")
install.packages("reshape2")
install.packages("writexl")
install.packages("httr") # for configuring to airflow
install.packages("stringr")
install.packages("tidyr")
install.packages("readr")
install.packages("rhandsontable")
install.packages(c("readxl","Rcpp"))
install.packages("tibble")
install.packages("highcharter")
install.packages("BiocManager")
BiocManager::install("flowCore")
